### PR TITLE
Bugfixes

### LINKED ISSUE #3: Functions do not nest properly
When trying to implement more complicated logic, I ran into an issue where functions cannot be called from other functions repeatedly:

Example program:
```
1x0f1o
1x1f0f0f

1f
```

Expected output:
`00` (as function 0 should be called twice by f1)

Actual output: 
`0`

### LINKED ISSUE #4: Conditionals do not end if the condition is not taken
Example program:
```
1x0f1o

2x0v1a
3x0v0l0e
```

Expected behavior: 
Interpreter error (`e`is a conditional operator and cannot be called from opcode 0, and the interpreter has to go back to opcode 0 after `l`)

Actual behavior:
Runs without printing anything

Note:
While the ability to use multiple conditionals for one check seems kind of useful - for example to implement an if-then-else construct - it doesn't work either, because as soon as the condition is met, the opcode switches back to 0, resulting in a runtime exception when encountering the next conditional instruction

### PR DESCRIPTION
**Pull request by tobiasheineken**
After minimizing the examples for #3 and #4, the diff to fix these issues way pretty obvious, so I decided to fork the project and fix these issues myself.

As I'm not used to npm and their modules I'm unsure if this PR should increase the version in package.json.
Let me know if you feel that's necessary.

### CODE REVIEW

**Comment by sporeball** [comment]
both of these commits produce the expected behavior for your provided example programs, but not for some of my own examples. nevertheless, thank you for reporting.
i'll take some time to remind myself how mocha and chai work, set up a large test suite, and if you can fix your fork to return what's expected for every case, i'll merge.
also, naz being 1.0.0 was just meant as a placeholder value since i never intended to publish it to the global namespace, but i'll consider incrementing it anyway.

**Comment by tobiasheineken** [comment]
I've fixed a bug in my implementation I stumbled into today.
I do think a test suite could be a good idea.
However, it might be useful to show a sample program and its expected behavior so I can start working on the issue.

**Comment by sporeball** [comment]
example program: `2a2x1v6m8m1a2x2v4a2x3v4a2x4v6a2x5v6a2x6v1x1f1r3x1v2e3x2v1e3x3v1e3x4v1e3x5v1e3x6v1e1o1f0x1x2f0a0x1r1o1f`
input: `potato`
expected output: `ptt`
actual output: throws the error `no input provided`

 is the control character STX (U+0002)
see [here](https://codegolf.stackexchange.com/a/203423/91030) for an explanation of this program

**Comment by tobiasheineken** [comment]
According to my understanding of your language, your program is an infinite loop.

It really comes down to: If a conditional is taken, does that represent a call, or a goto?
My Implementation assumes it's a call, this sample assumes it's a goto

Example program:
```
2x2v
1x0f1o
1x1f3x2v0e1o

1f
```

I expect it to be the following c program:
```c
int reg = 0
int mem[10];
int f0() {
  printRegister()
}

int f1() {
  if(reg == mem[2]) f0();
  printRegister();
}

int main() {
mem[2]= reg
  f1();
}
```

(which would print `00`)

But you could also assume conditionals to be gotos (which doesn't compile with c, but what can be emulated like this:

```c
int f1() {
  if (reg == mem[2]) {f0();} else {
    printRegister();
  }
}
```

(which prints `0`)

If you agree that it should be a call, your sample can be fixed easily by adding `1h` at the end of f2, halting the program when f2 finished executing

**Comment by sporeball** [comment]
that's correct. the program is intended to loop over the contents of the file infinitely, with STX being the halt condition.
conditionals were always intended to act like gotos, not calls; the `h` command was added early in development and was never meant to be used for breaking out of an infinite loop - only for debugging.
in fact, output shouldn't actually be printed if the `h` command is encountered, but that's its own issue.

**Comment by tobiasheineken** [comment]
While I do not agree with this kind of definition, i've got a fix for that in the pipeline, it's going to be pushed soon.

Could you adjust the documentation to make that even clearer?

EDIT: I don't think it's a good idea to stop printing the output if `h` is encountered. It's a very powerful tool to be able to exit multiple levels of function calls, so I think `h` should stay as it is right now.

**Review by sporeball — APPROVED** [review]
decided to take another peek at this, and it seems to work perfectly.
will formally collect more test cases tomorrow, and merge if it stays that way.

**Comment by tobiasheineken** [comment]
Is everything OK with this PR or do you need me for anything?

I could rebase these commits onto master if you think that's helpful, or you could just cherry-pick them.
It's your call.

**Comment by sporeball** [comment]
nice of GitHub to immortalize my indecision on whether the link is necessary.
thanks again for the bugfixes!
i'll port them to the web interpreter later, pending a full refactor like in 71d9992.

**Comment by sporeball** [comment]
**finally** ported this to the web interpreter. the prime example works out of the box :)
let me know if you run into any more issues.

**Pull request merged**
